# Generated by Django 5.1.6 on 2025-02-19 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='r_playlists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
                ('playlist_id', models.TextField()),
                ('thumbnail', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='r_videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
                ('video_id', models.TextField()),
                ('thumbnail', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='c_playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
                ('Playlist_id', models.TextField()),
                ('thumbnail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_playlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='c_videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
                ('video_id', models.TextField()),
                ('thumbnail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesAndSubcategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250)),
                ('sub_category', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_and_subcategories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=250)),
                ('Playlist_id', models.ManyToManyField(related_name='c_playlist', to='recommendations.c_playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_course', to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ManyToManyField(related_name='c_video', to='recommendations.c_videos')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_id', models.TextField()),
                ('playlist_name', models.TextField(max_length=500)),
                ('total_videos', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.TextField()),
                ('video_name', models.CharField(max_length=500)),
                ('total_video_length', models.TextField()),
                ('video_view_length', models.TextField(default=0)),
                ('playlist', models.TextField()),
                ('channel_id', models.TextField()),
                ('category', models.CharField(max_length=250)),
                ('video_thumbnail', models.TextField()),
                ('playlist_thumbnail', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
